name: rainfrog
base: core24
version: 'v0.3.14'
license: MIT
summary: Unofficial rainfrog cli app
description: |
  rainfrog is a database tool for the terminal.
platforms:
  amd64:
  arm64:
grade: stable
confinement: strict
apps:
  rainfrog:
    command: rainfrog
    environment:
      RAINFROG_CONFIG: $SNAP_USER_COMMON
      RAINFROG_FAVORITES: $SNAP_USER_COMMON/favorites
    plugs:
      - home
      - network
      - network-bind
parts:
  rainfrog:
    plugin: dump
    source-type: tar
    source:
      - on amd64: https://github.com/achristmascarl/rainfrog/releases/download/${SNAPCRAFT_PROJECT_VERSION}/rainfrog-${SNAPCRAFT_PROJECT_VERSION}-x86_64-unknown-linux-musl.tar.gz
      - on arm64: https://github.com/achristmascarl/rainfrog/releases/download/${SNAPCRAFT_PROJECT_VERSION}/rainfrog-${SNAPCRAFT_PROJECT_VERSION}-aarch64-unknown-linux-musl.tar.gz
